spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://dpg-cl0o0is8s0fs73ds1gj0-a.oregon-postgres.render.com:5432/produtos_banco
    password: TnSt4XBX5kzE2WOQvQS5VvNOCu0c1qvj
    username: admin
    driverClassName: org.postgresql.Driver
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: smtp.gmail.com
    username: guilhermevmachado558@gmail.com
    password: "icgz npsb ezma xual"
    port: '587'
